### ISSUE TITLE
Will JitPicker be merged into Fuzzilli in the future?

### ISSUE THREAD

**Issue by chennbnbnb** [RUB-SysSec/JIT-Picker#4]
I notice that: JitPicker is already lagging far behind Fuzzilli, and last merge request have been closed.
So I wodner will JitPicker be merged into Fuzzilli in the future?

**Comment by bernhl** [comment]
I'm not currently working on JIT-Picker, however I plan to come back to the project in May. I intend to rebase it onto the latest Fuzzilli commit and verify that it works on jsc/v8/sm. Whether the JIT-Picker changes will be merged into mainline Fuzzilli is not decided though.

**Comment by chennbnbnb** [comment]
I have implemted `Fuzzilli_hash()` in v8, and i am trying to use JitPicker fuzz v8. 
I find that JitPicker report some non-reproducible differentials,  One execHash is the same as the one I executed manually, the other is different
Exploration mutaiton has been disbaled and I am sure it's not `Fuzzilli_hash()`'s problem
it seem that: `Fuzz_hash()` fuzzilli_hash() was passed different values in two identical programs, do you have any idea about this problem?

**Comment by bernhl** [comment]
I did observe a similar effect in spidermonkey. The root cause of this effect is still unclear to me; I guess I'll `rr` trace the respective executions to figure out what's going wrong.

**Comment by chennbnbnb** [comment]
OK, thank you
